spring:
    application:
        name: spring-config-client-change
server:
    port: 9090
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true