

spring:
  application:
    name: provider-demo
server:
  port: 9091


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


local:
  file:
    store-path: d:/file-center/
